### ISSUE TITLE
Final report draft feedback

### ISSUE THREAD

**Issue by rossbar** [berkeley-stat159/project-gamma#55]
- No "report2" etc... see general feedback - git eliminates the need for 
   doing things like this!
 - I'm unclear: are the preprocessing steps you enumerate things that you did,
   or things that the data hosts did? If these are things that you did, it is
   much more compelling if you show images that display the results of these
   preprocessing steps along with the description.
 - The notes on the data in section 3.2.1 should probably be discussed in the
   data section instead.
 - In section 3.2.1 - good description of your regressors; I'd like to
   see the design matrix as well though
 - For the results in section 4, it's unclear to me what you are displaying. Are
   these results from a single subject? All subjects? All subjects from the
   control group? - make sure to be specific about what you are showing
 - Figure 4 in section 4.2 might be more clear if you grouped all of the 
   scizophrenics together and the controls together instead of staggering them

**Comment by LiamFengLin** [comment]
Thank you so much Ross!
