### ISSUE TITLE
Potential problem during grading: Long download time for 20 subjects. 

### ISSUE THREAD

**Issue by LiamFengLin** [berkeley-stat159/project-gamma#70]
Hi @jarrodmillman,

There was a portion in the project where we analyzed data from 20 subjects. The BOLD images (the standard mni preprocessed version) themselves take around 1.5 hours to download. 

The part that takes unnecessarily long time is the condition files because they are bundled together with the rest of the raw data on the openfMRI website. (We are only using the condition files, not the raw data for this portion of the project) 

Since they are just text files, would it be okay for us to include those txt files in the repo but leaves clear explanation in README? We will also include instructions on how to download them as an option so to ensure reproducibility. 

Thank you so much!

**Comment by LiamFengLin** [comment]
@matthew-brett 

Hi Matthew I added you here as well just to keep you updated. 

Thank you for your help!

**Comment by matthew-brett** [comment]
Yes, absolutely - that's a good idea to include the text files.  You might want to add a license for those files, from the OpenFMRI license, so people know where they came from.

**Comment by LiamFengLin** [comment]
Thank you!
