### ISSUE TITLE
Necessity of Python3 compatibility 

### ISSUE THREAD

**Issue by LiamFengLin** [berkeley-stat159/project-gamma#78]
Hi @matthew-brett ,

I got the idea that we were always using python2 for our codebase but a piazza post seemed to suggest that our code need to run in python3 as well. May I ask whether it is necessary for us to make our code run in both python2 and python3 or can we stick to only python2 (meaning removing python3 from travis.yml file)

Thank you!

**Comment by matthew-brett** [comment]
Jarrod and Ross will be marking, but I think you should treat Python 3 compatibility as a marker of code quality.   So, Jarrod and Ross will check reproducibility using whichever Python you use by default, but they will take into account whether you have Python 3 compatibility in assessing the quality of your code and its longevity (Python 2 will likely start going out of use in a few years).

If you stuck on Python 3 issues, I suggest you send us an `@` mention to ask for help with fixing Python 3 and meanwhile keep working on Python 2.

@jarrodmillman @rossbar - any comments or corrections?

**Comment by LiamFengLin** [comment]
Thank you! I adapted the code to be compatible with both 3 and 2.
