### ISSUE TITLE
Berkeley SCF login info

### ISSUE THREAD

**Issue by rossbar** [berkeley-stat159/project-gamma#87]
Here is the login info for your SCF accounts. If you don't remember your passwords, I can't really help you there!

lynnzhao: s159-48
LiamFengLin: s159-42
nhejazi: s159-2
z357412526: s159-47

**Comment by LiamFengLin** [comment]
Hi Ross,

Thanks for the account info!

I tried to pip install on the stats instructional machine but I encountered some permission denied errors since I don't have root privilege so I basically cannot test anything there. 

Is there an easy way to get around that?

**Comment by rossbar** [comment]
You can try the --user option to pip to try to install it locally
