### ISSUE TITLE
How big is the data after downloading/unpacking

### ISSUE THREAD

**Issue by rossbar** [berkeley-stat159/project-gamma#91]
(It would be nice if this was in your README)

**Comment by LiamFengLin** [comment]
Hi Ross!

Sorry about that. It is about 15G (this is for the Recommended Steps).

**Comment by rossbar** [comment]
Thanks, I will try to download everything now

**Comment by rossbar** [comment]
I'm about to put a piazza announcement out about project build issues. You guys are a special case because I didn't attempt to run everything until I got confirmation on the data size an hour ago. 

I was able to download and validate the data successfully, and am running the analysis now (successfully so far, it's on the network_analysis.py at the moment). I just wanted to let you guys know that so far you are in the same category as beta and theta: the build instructions have worked up to the analysis point. I will follow up with you guys when the analysis complets.

**Comment by LiamFengLin** [comment]
Thank you for the notice!

**Comment by rossbar** [comment]
Just wanted to let you know that your analysis finished successfully with no errors :+1: 

I haven't built the report yet, but I was very pleased that this worked - clearly your testing on another machine was a great idea!

**Comment by LiamFengLin** [comment]
Thank you! 

Now I can step into finals with a relief :D

**Comment by LiamFengLin** [comment]
It is most likely an overkill but for future semesters, giving everyone a preconfigured vm image (e.g. Vagrant) might help to standardize testing :D

**Comment by rossbar** [comment]
Even VM's aren't bulletproof, especially for cases where hardware is involved (although this doesn't really apply to any of your projects). Our plan was to have groups pair off with each other and have everyone in one group try to build and run the other group's project and vice-versa. Unfortunately, we got so busy that this just slipped through the cracks. Thanks for the suggestions though :+1:
